apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-recommender
  namespace: argocd
spec:
  project: glaubersantos-project
  
  source:
    repoURL: 'https://github.com/glauberss2007/spotify-recommender.git'
    path: 'kubernetes'
    targetRevision: HEAD
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: glaubersantos
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
