apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc
  namespace: glaubersantos
spec:
  selector:
    matchLabels:
      namespace: glaubersantos
  storageClassName: default-storage-class-glaubersantos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
