apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: glaubersantos
spec:
  selector:
    app: spotify-recommender
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30502
  type: NodePort
